name: Deploy
on:
  push:
    branches: deno-edge
  pull_request:
    branches: deno-edge

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task build:wasm"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "bundlejs"
          entrypoint: "packages/edge/mod.ts"
          root: ""
